# psql -U postgres
# create user email_grabber with password 'pooPhee6';
# create database email_grabber owner email_grabber;

template: &template
  adapter:  postgresql
  encoding: unicode
  database: email_grabber
  username: email_grabber
  password: pooPhee6


development:
  <<: *template


production:
  <<: *template

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
