# psql -U postgres
# create user email_grabber with password 'pooPhee6';
# create database email_grabber owner email_grabber;

template: &template
  adapter:  postgresql
  encoding: unicode
  database: blog_database
  username: blogger
  password: bieNg9haV


development:
  <<: *template


production:
  <<: *template

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
