# coding: utf-8

template: &template
  min_prefix_len: 0 
  min_infix_len:  1 
  min_word_len:   1 
  charset_type:   utf-8 
  morphology:     stem_ru 
  charset_table:  "0..9, a..z, _, @, A..Z->a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F"

development:
  <<: *template

production:
  <<: *template
